name: "Help Wanted / 问题请求"
description: Submitting question inquiries / 提交问题请求
title: "[Help Wanted]: "
labels: ["question", "help wanted"]
assignees:
  - deuso
  - LaurenIsACoder

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting your question! Please fill out the template below so we can better assist you.  
        感谢您提交问题！请按照以下模板填写，以便我们更好地帮助您。

  - type: input
    id: summary
    attributes:
      label: Summary / 问题概述
      description: Please briefly describe your question. / 请简要描述您的问题。
      placeholder: Enter a summary of your question here / 在这里输入问题概述
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Detailed Description / 详细描述
      description: Please provide a detailed description of your question, including background information and attempted solutions.  
                   / 请详细描述您的问题，包括背景信息、尝试过的解决方法等。
      placeholder: Enter a detailed description here / 在这里输入详细描述
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information / 环境信息
      description: Specify the environment where the bug occurred (e.g., OS, version, or commit hash). / 指定错误发生的环境（例如：操作系统、版本或提交哈希号）。
      placeholder: Enter environment details (e.g., OS, version, commit hash) / 输入环境详细信息（例如：操作系统、版本、提交哈希号）
      value: |
        **OS**: [e.g., Loongnix, etc.]
        **操作系统**: [例如：龙芯操作系统等]

        **Kernel Version**: [e.g., 5.4.0, etc.]
        **Linux 内核版本**: [例如：5.4.0等]

        **GCC Version**: [e.g., 9.3.0, etc.]
        **GCC 版本**: [例如：9.3.0等]

        **GLIBC Version**: [e.g., 2.31, etc.]
        **GLIBC 版本**: [例如：2.31等]

        **LAT Version / Commit Hash**: [e.g., 1.6.0, abc1234, etc.]
        **LAT 版本号 / 提交 Hash**: [例如：1.6.0, abc1234等]


  - type: textarea
    id: additional
    attributes:
      label: Additional Information / 补充信息
      description: If there is any additional information, please provide it here.  
                   / 如果有其他需要补充的信息，请在这里填写。
      placeholder: Enter additional information here (optional) / 在这里输入补充信息（可选）
